### ISSUE TITLE
Aw shit here we go again

### ISSUE THREAD

**Issue by HausemasterIssue** [Sxmurai/nebula#1]
All you had to do was not rewrite Inferno for the 4th time CJ!

**Comment by xgraza** [comment]
5th time if you count the original original version, before the Inferno repo on my github even existed

**Comment by master7720** [comment]
already like 4 clients named neblua

**Comment by HausemasterIssue** [comment]
Kotlin The Java Skid

**Comment by xgraza** [comment]
kotlin better
